### ISSUE TITLE
Volume not saving when you go to another video.

### ISSUE THREAD

**Issue by Thehail** [wdwind/YouTubeVolumeMouseController#1]
Hello! The script looks pretty good but when you go from a video to another, the volume doesn't save. It might be intentionally, then can I request a similar script but saving the volume for every video?

**Comment by wdwind** [comment]
Hi Thehail, thank you. 

This is indeed a bug which I didn't notice before. I have published a new version (`1.5.0`). Please update the script and try it again. Now the volume is persisted during video switch.

Having said that, working with YouTube is also very tricky, I can't guarantee that the new version will work on all OS/browsers. Please let me know if there are other issues.

**Comment by Thehail** [comment]
Thank you!
