### ISSUE TITLE
Pattern is to broad, Should include only pages with player

### ISSUE THREAD

**Issue by senpl** [wdwind/YouTubeVolumeMouseController#2]
I think pattern should match only pages that on which video is played. It probably should not be active on pages that not play video. So active on pages with `v=` and channels page, inactive on pages like search results and without active player.

**Comment by wdwind** [comment]
Hi, YouTube site doesn't reload pages on navigation, instead it replaces the history state. If the script is restricted to video pages (`v=`), it won't work in the case user navigating from search page to the video page.

Check [this](https://stackoverflow.com/a/34100952/4214478) stackoverflow answer for more details.
