### ISSUE TITLE
滾論能控制音量的區域

### ISSUE THREAD

**Issue by leadra** [wdwind/YouTubeVolumeMouseController#5]
https://www.youtube.com/watch?v=ibpV3nL778I
目前[#縦画面歌枠]
滑鼠如果在黑背景，無法調整音量
還有在控制列也無法調整，能加入嗎?
![image](https://github.com/user-attachments/assets/c15b961f-21c7-46d5-b90b-70095a30cffb)

**Comment by wdwind** [comment]
Embedded video is supported now.

**Comment by leadra** [comment]
黑色區域仍無法控制音量。
但非常感謝嵌入影片embed的支援!!
