### ISSUE TITLE
Volume Scroll not working

### ISSUE THREAD

**Issue by SleepDaemon** [wdwind/YouTubeVolumeMouseController#6]
I came back from a trip and didnt take my laptop with me, but when I got back and started using like normal (I got use to using with the script) the volume wasnt changing when I scrolled. 

That is really all I have, I am on latest version and do not know what really causing the problem. I just got back and found it not working.

**Comment by wdwind** [comment]
What's the browser? Did refresh help? Or if you can open the console and check if there are any specific error message, that would be more helpful for me to figure out the issue.

**Comment by SleepDaemon** [comment]
I am on Firefox, and here is all the yellow and reds from the console
![image](https://github.com/user-attachments/assets/8fa9bb95-8992-4cc2-a5bc-f4fc3f44a51d)
![image](https://github.com/user-attachments/assets/a263fa4b-caf4-48e7-8002-c63b59c4faab)
![image](https://github.com/user-attachments/assets/9c4a6d6a-e645-4a19-9bae-ff3c54731292)

**Comment by SleepDaemon** [comment]
Ok so i noticed this, it works for few seconds but then the video pauses and goes black. I get the load/buffer icon for a sec or two and then goes back playing the video but feature doesnt work after that.

**Comment by SleepDaemon** [comment]
it seems 6-10 seconds into the video it stops working

**Comment by SleepDaemon** [comment]
@wdwind Guessing this is not important much

**Comment by wdwind** [comment]
Screenshot didn't show anything interesting. Can you provide the video URL?

**Comment by SleepDaemon** [comment]
> Screenshot didn't show anything interesting. Can you provide the video URL?

it happens on every video

**Comment by SleepDaemon** [comment]
[console-export-2024-10-5_9-10-22.txt](https://github.com/user-attachments/files/17265309/console-export-2024-10-5_9-10-22.txt)

Exported the entire console

**Comment by SleepDaemon** [comment]
ok so i found a pattern, only at the start of the video does this happens. Once the video passes idk the 10-15 second mark it goes black for second and comes back with the volume control disabled. However if you reload the page where it should reload to your last place you were on the video, so after the 10-15sec. The volume control script works fine and doesnt go away.

**Comment by wdwind** [comment]
Nothing interesting found from the console log you provide. Please try to reproduce in a clean browser and clean setup.

**Comment by SleepDaemon** [comment]
the issue doesnt occur when im in private/incog mode on firefox

**Comment by SleepDaemon** [comment]
Ok I did what you said, I tried disabling all extensions except violentmonkey, and I still get the issue but in incog/private mode i dont. I think I'll just roll back to before v1.5.0, how do I do that?

**Comment by SleepDaemon** [comment]
> ok so i found a pattern, only at the start of the video does this happens. Once the video passes idk the 10-15 second mark it goes black for second and comes back with the volume control disabled. However if you reload the page where it should reload to your last place you were on the video, so after the 10-15sec. The volume control script works fine and doesnt go away.

Ye like I said here only it stops working after the video passes the 10-12sec mark, on some it is the 8 second mark. Then if I reload after it does that blacking out bit the script works again and it doesn't do the blacking out. So the issue occurs only at the start of the video.

**Comment by wdwind** [comment]
> the issue doesnt occur when im in private/incog mode on firefox

This indicates the issue is on browser side. Not too much else I can help here. Maybe you can try to re-install the browser.

**Comment by SleepDaemon** [comment]
> > the issue doesnt occur when im in private/incog mode on firefox
> 
> This indicates the issue is on browser side. Not too much else I can help here. Maybe you can try to re-install the browser.

but i didnt have this issue in previous version

**Comment by SleepDaemon** [comment]
Ok so every time the thing happens this shows in the console

![image](https://github.com/user-attachments/assets/badaa462-6dca-475e-a010-82b5ff0c31ad)

**Comment by SleepDaemon** [comment]
Look I don't wanna reinstall my browser go through resetting things up again (installing extensions, login into sites, reapplying my Firefox CSS skin) just for this one script, just provide me older versions of the code of the script. If they work I rather use that then reinstall and if they dont then ill go through the trouble of reinstalling.

**Comment by wdwind** [comment]
https://greasyfork.org/en/scripts/376002-youtube-volume-mouse-controller/versions

**Comment by SleepDaemon** [comment]
I reinstalled by browser, worse part i forgot to backup extension settings and what not, and even after all that. The issue still persists even on older versions. I did restore my cookies though.
